### PR TITLE
Fix hadolint error and migrate to composite run actions

### LINKED ISSUE #30: Migrate from docker to composite run actions
Links:
* https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps
* https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

Inspiration:
* https://github.com/reviewdog/action-golangci-lint/pull/46
* https://github.com/reviewdog/action-tflint/pull/28

### LINKED ISSUE #33: File not found error
I'm trying to run this action using the provided example workflow in the README but I get an error when my workflow runs. I have reproduced the error in an [example repo](https://github.com/benregn/reviewdog-hadolint-action-problem). The error can be seen in [this check](https://github.com/benregn/reviewdog-hadolint-action-problem/pull/1/checks?check_run_id=1556173590#step:4:13).

Side note: If I don't supply the `exclude` option, I get this error `fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`. Not sure if related.

### PR DESCRIPTION
**Pull request by mgrachev**
```
hadolint:  : openBinaryFile: does not exist (No such file or directory)
```

Close #30, #33

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -1,11 +1,16 @@
 #!/bin/sh
 
+# set -xv
+set +H
```
Comment (limakzi) [inline entrypoint.sh]: Isn't it a non-interactive shell?

> The shell supports a history expansion feature that is similar to the history expansion in csh. This section describes what syntax features are available. This feature is enabled by default for interactive shells, and can be disabled using the +H option to the set builtin command (see SHELL BUILTIN COMMANDS below). Non-interactive shells do not perform history expansion by default.

File: entrypoint.sh [hunk 2]
```diff
@@ -1,11 +1,16 @@
...
+
 cd "$GITHUB_WORKSPACE" || exit
 export REVIEWDOG_GITHUB_API_TOKEN="${INPUT_GITHUB_TOKEN}"
 
+echo $INPUT_EXCLUDE;
```
Comment (limakzi) [inline entrypoint.sh]: There is no reason to print `INPUT_EXCLUDE` unless debug mode or tracing is enabled.

File: entrypoint.sh [hunk 3]
```diff
@@ -1,11 +1,16 @@
...
+
 EXCLUDES=""
 for exclude_path in $INPUT_EXCLUDE; do
-  EXCLUDES="$EXCLUDES --exclude='!$exclude_path'"
+  EXCLUDES+=" --exclude='!$exclude_path'"
```
Comment (limakzi) [inline entrypoint.sh]: This operator is not compliant with POSIX.
Either we change the interpreter to `bash` or change the way you set a variable to:
```
EXCLUDES="$EXCLUDES <set of excludes>
```

File: entrypoint.sh [hunk 4]
```diff
@@ -15,12 +20,34 @@ done
 
 INPUT_HADOLINT_FLAGS="$INPUT_HADOLINT_FLAGS $IGNORE_LIST"
 
-git ls-files --exclude='*Dockerfile*' --ignored "${EXCLUDES}" \
-  | xargs hadolint "${INPUT_HADOLINT_FLAGS}" \
+echo "--- EXCLUDES ---"
```
Comment (limakzi) [inline entrypoint.sh]: Do not echo that in a standard mode.

File: entrypoint.sh [hunk 5]
```diff
@@ -15,12 +20,34 @@ done
...
+echo "3 git ls-files"
+git ls-files --exclude='*Dockerfile*' --ignored $EXCLUDES
+
+# echo "3 with xargs"
+# git ls-files --exclude='*Dockerfile*' --ignored \
+#   | xargs hadolint ${INPUT_HADOLINT_FLAGS} \
+
+# echo "4 with xargs"
+# git ls-files --exclude='*Dockerfile*' --ignored ${EXCLUDES} \
+#   | xargs hadolint ${INPUT_HADOLINT_FLAGS} \
```
Comment (limakzi) [inline entrypoint.sh]:
```suggestion
```

**Review by limakzi — CHANGES_REQUESTED** [review]
